USE [ZTREEDB]
GO

/****** Object:  Table [dbo].[ZTree]    Script Date: 2016/7/24 17:03:45 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[ZTree](
	[Id] [int] NOT NULL,
	[PId] [int] NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
	[Open] [bit] NOT NULL CONSTRAINT [DF_ZTree_Open]  DEFAULT ((1)),
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


